spring:

  profiles:
    active: dev

  datasource:
    url: "jdbc:postgresql://localhost:5432/koko"
    username: "postgres"
    password: "postgres"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwtSecret: kokosecret
jwtExpirationMs: 86400000
